#include "ComputeRotationMatrixFromTORTOISETransformations_parser.h"
#include <algorithm>
#include <ctype.h>



ComputeRotationMatrixFromTORTOISETransformations_PARSER::ComputeRotationMatrixFromTORTOISETransformations_PARSER( int argc , char * argv[] )
{
    CreateParserandFillText(argc,argv);    
    this->Parse(argc,argv);
    
           
    if( argc == 1 )
    {
        this->PrintMenu( std::cout, 5, false );
        exit(EXIT_FAILURE);
    }
    
    if(checkIfAllRequiredParamsAreEntered()==0)
    {
        std::cout<<"Not all the required Parameters are entered! Exiting!"<<std::endl;
        exit(EXIT_FAILURE);
    }   
} 



ComputeRotationMatrixFromTORTOISETransformations_PARSER::~ComputeRotationMatrixFromTORTOISETransformations_PARSER()
{       
}


void ComputeRotationMatrixFromTORTOISETransformations_PARSER::CreateParserandFillText(int argc, char* argv[])
{  
    this->SetCommand( argv[0] );
 
    std::string commandDescription = std::string( "This program combines all the provided transformations that were generated by TORTOISEProcess into a single deformation field and applies it to the input 4D image. " );
    
    this->SetCommandDescription( commandDescription );    
    this->InitializeCommandLineOptions();        
}


void ComputeRotationMatrixFromTORTOISETransformations_PARSER::InitializeCommandLineOptions()
{
    typedef itk::ants::CommandLineParser::OptionType OptionType;
   
    {
        std::string description = std::string( "Full path to the 4D original raw DWI image that was input to TORTOISEProcess" );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'i');
        option->SetLongName( "input_img");
        option->SetDescription( description );
        this->AddOption( option );
    }
    {
        std::string description = std::string( "Volume Index of the DWI for which the rotation amtrix will be output. Zero-based." );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'v');
        option->SetLongName( "vol");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to structural template image. After TORTOISEProcess this is generally called structural_0.nii" );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 't');
        option->SetLongName( "template");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to the motion \& eddy currents distortion correction file. TORTOISEProcess outputs this with the name xxx_moteddy_transformations.txt . Only provide it if the input image is NOT in the b=0 image space but that of a DWI. The number of lines in this file should match the number of volumes in the input 4D image (optional)" );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'm');
        option->SetLongName( "moteddy");
        option->SetDescription( description );
        this->AddOption( option );
    }    

    {
        std::string description = std::string( "Full path to blip down to blip up transformation. ONLY provide it if the input image is is in blip down space. Typically named bdown_to_bup_rigidtrans.hdf5 (optional) " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'd');
        option->SetLongName( "blipdown");
        option->SetDescription( description );
        this->AddOption( option );
    }


    {
        std::string description = std::string( "Full path to blip_up b=0 to structural image transformation file. Typically named b0_to_str_rigidtrans.hdf5 (optional) " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 's');
        option->SetLongName( "b02str");
        option->SetDescription( description );
        this->AddOption( option );
    }
}

std::string ComputeRotationMatrixFromTORTOISETransformations_PARSER::getInputImageName()
{
    OptionType::Pointer option = this->GetOption( "input_img");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
       return std::string("");
}

int ComputeRotationMatrixFromTORTOISETransformations_PARSER::getVolIndex()
{
    OptionType::Pointer option = this->GetOption( "vol");
    if(option->GetNumberOfFunctions())
        return atoi(option->GetFunction(0)->GetName().c_str());
    else
        return 0;
}


std::string ComputeRotationMatrixFromTORTOISETransformations_PARSER::getTemplateName()
{
    OptionType::Pointer option = this->GetOption( "template");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string ComputeRotationMatrixFromTORTOISETransformations_PARSER::getMotionEddyParametersName()
{
    OptionType::Pointer option = this->GetOption( "moteddy");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string ComputeRotationMatrixFromTORTOISETransformations_PARSER::getBlipDownToUpTransformationName()
{
    OptionType::Pointer option = this->GetOption( "blipdown");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string ComputeRotationMatrixFromTORTOISETransformations_PARSER::getBo2StrTransformationName()
{
    OptionType::Pointer option = this->GetOption( "b02str");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

bool ComputeRotationMatrixFromTORTOISETransformations_PARSER::checkIfAllRequiredParamsAreEntered()
{
    
    if(this->getInputImageName()==std::string(""))
    {
        std::cout<<"Input image name not entered...Exiting..."<<std::endl;
        return 0;
    }

    return 1;
}




