#include "CombineALLTransformations_parser.h"
#include <algorithm>
#include <ctype.h>



CombineALLTransformations_PARSER::CombineALLTransformations_PARSER( int argc , char * argv[] )
{
    CreateParserandFillText(argc,argv);    
    this->Parse(argc,argv);
    
           
    if( argc == 1 )
    {
        this->PrintMenu( std::cout, 5, false );
        exit(EXIT_FAILURE);
    }
    
    if(checkIfAllRequiredParamsAreEntered()==0)
    {
        std::cout<<"Not all the required Parameters are entered! Exiting!"<<std::endl;
        exit(EXIT_FAILURE);
    }   
} 



CombineALLTransformations_PARSER::~CombineALLTransformations_PARSER()
{       
}


void CombineALLTransformations_PARSER::CreateParserandFillText(int argc, char* argv[])
{  
    this->SetCommand( argv[0] );
 
    std::string commandDescription = std::string( "This program combines all the provided transformations that were generated by TORTOISEProcess into a single deformation field and applies it to the input 4D image. " );
    
    this->SetCommandDescription( commandDescription );    
    this->InitializeCommandLineOptions();        
}


void CombineALLTransformations_PARSER::InitializeCommandLineOptions()
{
    typedef itk::ants::CommandLineParser::OptionType OptionType;
   
    {
        std::string description = std::string( "Full path to the 4D image to which the transformations will be applied to." );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'i');
        option->SetLongName( "input_img");
        option->SetDescription( description );
        this->AddOption( option );
    }
    {
        std::string description = std::string( "Full name of the transformed 4D imageto be output" );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'o');
        option->SetLongName( "output_img");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to template image. The space of this image will be used to output the transformed input image." );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 't');
        option->SetLongName( "template");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to the motion \& eddy currents distortion correction file. TORTOISEProcess outputs this with the name xxx_moteddy_transformations.txt . Only provide it if the input image is NOT in the b=0 image space but that of a DWI. The number of lines in this file should match the number of volumes in the input 4D image (optional)" );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'e');
        option->SetLongName( "moteddy");
        option->SetDescription( description );
        this->AddOption( option );
    }
    {
        std::string description = std::string( "Phase encoding direction. vertical or horizontal . MUST be provide if moteddy file is provided." );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'p');
        option->SetLongName( "PE");
        option->SetDescription( description );
        this->AddOption( option );
    }
    {
        std::string description = std::string( "Rotation center for eddy currents. isocenter or center_voxel or center_slice .  ONLY provide it if you provided this during TORTOISEProcess " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'r');
        option->SetLongName( "rot_center");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to blip down to blip up transformation. ONLY provide it if the input image is is in blip down space. Typically named bdown_to_bup_rigidtrans.hdf5 (optional) " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'd');
        option->SetLongName( "blipdown");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to gradient nonlinearity  distortion field (as generated by TORTOISEProcess) (optional) " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'g');
        option->SetLongName( "nonlin");
        option->SetDescription( description );
        this->AddOption( option );
    }

    {
        std::string description = std::string( "Full path to susceptibility distortion file. deformation_FINV.nii.gz for up and deformation_MINV.nii.gz for down data (optional) " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 's');
        option->SetLongName( "epi");
        option->SetDescription( description );
        this->AddOption( option );
    }
    {
        std::string description = std::string( "Full path to blip_up b=0 to structural image transformation file. Typically named b0_to_str_rigidtrans.hdf5 (optional) " );
        OptionType::Pointer option = OptionType::New();
        option->SetShortName( 'f');
        option->SetLongName( "b02str");
        option->SetDescription( description );
        this->AddOption( option );
    }
}


std::string CombineALLTransformations_PARSER::getPE()
{
    OptionType::Pointer option = this->GetOption( "PE");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("vertical");
}

std::string CombineALLTransformations_PARSER::getRotCenter()
{
    OptionType::Pointer option = this->GetOption( "rot_center");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("isocenter");
}

std::string CombineALLTransformations_PARSER::getInputImageName()
{
    OptionType::Pointer option = this->GetOption( "input_img");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
       return std::string("");
}
std::string CombineALLTransformations_PARSER::getOutputName()
{
    OptionType::Pointer option = this->GetOption( "output_img");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string CombineALLTransformations_PARSER::getTemplateName()
{
    OptionType::Pointer option = this->GetOption( "template");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string CombineALLTransformations_PARSER::getMotionEddyParametersName()
{
    OptionType::Pointer option = this->GetOption( "moteddy");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string CombineALLTransformations_PARSER::getBlipDownToUpTransformationName()
{
    OptionType::Pointer option = this->GetOption( "blipdown");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string CombineALLTransformations_PARSER::getGradientNonlinearityTransformationName()
{
    OptionType::Pointer option = this->GetOption( "nonlin");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string CombineALLTransformations_PARSER::getEPITransformationName()
{
    OptionType::Pointer option = this->GetOption( "epi");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

std::string CombineALLTransformations_PARSER::getBo2StrTransformationName()
{
    OptionType::Pointer option = this->GetOption( "b02str");
    if(option->GetNumberOfFunctions())
        return option->GetFunction(0)->GetName();
    else
        return std::string("");
}

bool CombineALLTransformations_PARSER::checkIfAllRequiredParamsAreEntered()
{
    
    if(this->getInputImageName()==std::string(""))
    {
        std::cout<<"Input image name not entered...Exiting..."<<std::endl;
        return 0;
    }

    return 1;
}




